import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import Delivery from "./components/Delivery";
import { GlobalContextProvider } from "../../context/store";

const inter = Poppins({ weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-black1 flex flex-col items-center`}>
        <GlobalContextProvider>
          <Navbar />
          <div>
            {children}
          </div>
          <Delivery />
          <Footer />
        </GlobalContextProvider>
      </body>
    </html>
  );
}
